-- MySQL Script generated by MySQL Workbench
-- Mon Nov 16 23:05:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema api_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `api_db` DEFAULT CHARACTER SET utf8 ;
USE `api_db` ;

-- -----------------------------------------------------
-- Table `api_db`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api_db`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `api_db`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `user` VARCHAR(60) NULL,
  `pass` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
